export const data = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    subscriptionDate: "2024-01-03",
    location: "Richmond, VA",
    tags: ["music", "concerts"],
    engagement: "Highly Engaged",
    art: "35 minutes",
  },
  {
    id: 2,
    name: "John Smith",
    email: "john.s@email.com",
    subscriptionDate: "2024-02-15",
    location: "Austin, TX",
    tags: ["sports", "fitness"],
    engagement: "Moderately Engaged",
    art: "22 minutes",
  },
  {
    id: 3,
    name: "Emily Davis",
    email: "emily.d@email.com",
    subscriptionDate: "2024-03-10",
    location: "Denver, CO",
    tags: ["books", "reading"],
    engagement: "Highly Engaged",
    art: "40 minutes",
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.b@email.com",
    subscriptionDate: "2024-04-22",
    location: "Seattle, WA",
    tags: ["tech", "gadgets"],
    engagement: "Low Engagement",
    art: "12 minutes",
  },
  {
    id: 5,
    name: "Jessica Wilson",
    email: "jessica.w@email.com",
    subscriptionDate: "2024-05-01",
    location: "Chicago, IL",
    tags: ["fashion", "style"],
    engagement: "Highly Engaged",
    art: "50 minutes",
  },
  {
    id: 6,
    name: "Daniel Lee",
    email: "daniel.l@email.com",
    subscriptionDate: "2024-06-18",
    location: "New York, NY",
    tags: ["travel", "adventure"],
    engagement: "Moderately Engaged",
    art: "28 minutes",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    email: "sophia.m@email.com",
    subscriptionDate: "2024-07-04",
    location: "Los Angeles, CA",
    tags: ["movies", "entertainment"],
    engagement: "Highly Engaged",
    art: "45 minutes",
  },
  {
    id: 8,
    name: "James White",
    email: "james.w@email.com",
    subscriptionDate: "2024-08-20",
    location: "Miami, FL",
    tags: ["sports", "fitness"],
    engagement: "Moderately Engaged",
    art: "30 minutes",
  },
  {
    id: 9,
    name: "Olivia Taylor",
    email: "olivia.t@email.com",
    subscriptionDate: "2024-09-09",
    location: "Boston, MA",
    tags: ["food", "cooking"],
    engagement: "Low Engagement",
    art: "15 minutes",
  },
  {
    id: 10,
    name: "William Anderson",
    email: "william.a@email.com",
    subscriptionDate: "2024-10-14",
    location: "San Francisco, CA",
    tags: ["tech", "startups"],
    engagement: "Highly Engaged",
    art: "52 minutes",
  },
];
